- name: Update Conda environment (if file exists)
  run: |
    if [ -f environment.yml ]; then
      conda env update --file environment.yml --name base
    else
      echo "⚠️ No environment.yml found, skipping Conda update"
    fi
